# Generated by Django 5.1.2 on 2024-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Accno', models.IntegerField(primary_key='accno', serialize=False)),
                ('Amount', models.IntegerField()),
                ('Interest', models.FloatField()),
                ('Startdate', models.DateField()),
                ('Phoneeno', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Enddate', models.DateField()),
            ],
        ),
    ]
